### ISSUE TITLE
write detector_z, not only in transformations

### ISSUE THREAD

**Issue by dperl-dls** [dials/nexgen#138]
because of autoPROC

**Comment by graeme-winter** [comment]
x GW
  o Global Phasing / proc-develop

"Good afternoon,

It looks to us that autoPROC is unhappy with the NeXus format we have just written (which I think is correct) using hyperion in place of GDA for data acquisition

I don’t know if you can still access our systems - the data are here

/dls/i03/data/2023/cm33866-4/TestInsulin/ins_10/ins_10_16_1_master.h5

but I can trivially copy to tmp somewhere

I think it relates to the distance - we encode the geometry (correctly, I believe) in the translation stack but it looks like autoPROC also depends explicitly on a detector_z field

We are looking at adding this but I wonder if it is worth you also using the geometry as encoded rather than the “miniCBF” parameters? Am happy to discuss - for us xia2/DIALS, fast_dp and xia2/XDS all work

As the master file is tiny I make the choice to attach it in case convenient

All the best Graeme"

I do not attach the file in question here

Anyhow, the race is now on

**Comment by DominicOram** [comment]
Should we have merged this? It means we're now not obeying the standard, right?

**Comment by noemifrisina** [comment]
I'll make an issue to remove it
